"""
Reporting Tool — Generates structured Markdown financial advisory reports.
"""

from models.user import UserProfile
from models.assessment import RiskAssessment
from config import get_logger

logger = get_logger(__name__)


def generate_report(
    profile: UserProfile,
    assessment: RiskAssessment,
    recs: list[dict],
) -> str:
    """
    Generate a complete Markdown advisory report.
    Returns the report as a string.
    """
    # Health score bar
    filled = int(assessment.health_score / 10)
    score_bar = "█" * filled + "░" * (10 - filled)

    # Risk profile colour hint
    risk_label = assessment.risk_profile.value.title() if hasattr(assessment.risk_profile, 'value') else str(assessment.risk_profile).title()

    # Goals section
    goals_lines = "\n".join(
        f"- {g.replace('_', ' ').title()}" for g in profile.goals
    ) if profile.goals else "- No specific goals set"

    # Plan steps
    plan_lines = "\n".join(
        f"{i+1}. {s}" for i, s in enumerate(assessment.plan_steps)
    ) if assessment.plan_steps else "No specific plan steps generated."

    # Recommendations
    rec_lines = "\n".join(
        f"- **{r['name']}** ({r['type']})"
        + (f" — {r['return_pct']}% projected return" if r.get("return_pct") else "")
        for r in recs
    ) if recs else "No products matched your current profile."

    report = f"""# Financial Advisory Report

## Financial Health Score
`{score_bar}` {assessment.health_score:.0f}/100

**Risk Profile:** {risk_label}

---

## Your Goals
{goals_lines}

---

## Financial Plan
{plan_lines}

---

## Recommended Products
{rec_lines}

---

*Report generated by Agentic Finance Advisor — for informational purposes only.*"""

    logger.info(f"Generated report for user_id={profile.user_id}")
    return report.strip()
